<?php 
return array (
  'site_name' => '商必营',
  'site_title' => '商必营-永久免费微信公众号第三方平台、微信营销和直达号运营服务平台',
  'site_logo' => '/tpl/Home/pigcms/common/images/logo-pigcms.png',
  'site_url' => 'http://www.31by.com',
  'site_twm' => '',
  'site_my' => '商必营',
  'site_chatkey' => 'f4dbc6f082efb06c8e4b4599acbabc56',
  'appid' => '',
  'secret' => '',
  'server_topdomain' => '31by.com',
  'connectout' => '用户已到期，请联系管理员或客服充值',
  'ischeckuser' => 'true',
  'reg_needmp' => 'true',
  'open_biz' => '0',
  'reg_groupid' => '1',
  'reg_validdays' => '30',
  'router_key' => '',
  'ipc' => '京ICP备12345678号',
  'site_qq' => '393173483',
  'site_mp' => '',
  'baidu_map_api' => 'C1HODB2NamuYAIHoIiMFWkWi',
  'site_email' => '393173483@qq.com',
  'keyword' => '商必营,免费微信第三方平台,微信公众平台,免费微信营销,微商城，微网站，微营销',
  'content' => '商必营是一家免费提供微信公众账号和直达号的服务开发平台，帮助企业打造微信营销，开通直达号。包含的功能有:微菜单、微服务、微统计、微支付、微商城、微官网、微会员、微活动、微推送、微客服等。',
  'countsz' => '',
  'copyright' => 'Copyright © 2015 商必营 提供源码 版权所有',
  'close_help' => '0',
);